// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type ContactPerson struct {
	Name      string `json:"name"`
	Mobile    string `json:"mobile"`
	Telephone string `json:"telephone"`
	Email     string `json:"email"`
}

type EnterpriseInfo struct {
	ID                 string           `json:"id"`
	EnterpriseID       string           `json:"enterprise_id"`
	EnterpriseCode     string           `json:"enterprise_code"`
	EnterpriseName     string           `json:"enterprise_name"`
	EnterpriseLevel    int              `json:"enterprise_level"`
	SuperiorEnterprise string           `json:"superior_enterprise"`
	Remark             string           `json:"remark"`
	ContactPerson      []*ContactPerson `json:"ContactPerson"`
	CreateAt           time.Time        `json:"create_at"`
	UpdateAt           time.Time        `json:"update_at"`
	DeleteAt           time.Time        `json:"delete_at"`
}

type NewEnterpriseInfo struct {
	EnterpriseName string `json:"enterprise_name"`
}

func (EnterpriseInfo) TableName() string {
	return "enterprise_info"
}
