// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

// 默认输入
type DefaultInput struct {
	// 页码
	Page int `json:"page"`
	// 每页返回的记录数
	Num int `json:"num"`
	// 排序方式，'oldest'和'newest'，默认为'newest'
	Sort string `json:"sort"`
}

// 驾驶员信息(暂把数据表中所有信息列出，实际使用时根据具体业务和安全性选择要返回的信息)
type DriverInfo struct {
	// 主键id
	ID string `json:"id"`
	// 驾驶员外部编码,由golang程序生成的xid，暴露到外部使用
	DriverID string `json:"driver_id"`
	// 所在企业id
	EnterpriseID string `json:"enterprise_id"`
}
